services:
  nginx:
    image: namelessmc/nginx:v2.1
    volumes:
      - ./web:/data
    depends_on: [php]
    cap_drop: ['ALL']
    cap_add: ['NET_RAW']
    mem_limit: 1024M
    cpus: 1
    ulimits:
      nofile: 50000
      nproc: 5000
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik
      - traefik.http.routers.nameless.rule=Host(`www.minersonline.uk`)
      - traefik.http.routers.nameless.entrypoints=websecure
      - traefik.http.services.nameless.loadbalancer.server.port=8080
      - traefik.http.routers.nameless.tls=true
      - traefik.http.routers.nameless.tls.certresolver=letsencrypt
      - traefik.http.routers.nameless.tls.domains[0].main=minersonline.uk
      - traefik.http.routers.nameless.tls.domains[0].sans=*.minersonline.uk
    restart: unless-stopped
    networks:
      - traefik
      - namelessmc

  php:
    image: namelessmc/php:v2.1
    volumes:
      - ./web:/data
      - target: /tmp
        tmpfs:
          size: 25M
        type: tmpfs
    depends_on: [db]
    cap_drop: ['ALL']
    cap_add: ['NET_RAW']
    cpus: 2
    mem_limit: 2048M
    read_only: true
    ulimits:
      nofile: 5000
      nproc: 5000
    restart: unless-stopped
    networks:
      - namelessmc

  db:
    image: mariadb
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MARIADB_USER: nameless
      MARIADB_DATABASE: nameless
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    restart: unless-stopped
    networks:
      - namelessmc

networks:
  namelessmc:
    name: namelessmc
  traefik:
    external: true
