services:
  php:
    image: php:8.5.7-fpm
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html:ro
    restart: unless-stopped
    networks:
      - mccms

  nginx:
    image: nginx:1.31.1
    depends_on:
      - php
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik
      - traefik.http.routers.nameless.rule=Host(`www.minersonline.uk`) || Host(`minersonline.uk`)
      - traefik.http.routers.nameless.entrypoints=websecure
      - traefik.http.services.nameless.loadbalancer.server.port=80
      - traefik.http.routers.nameless.tls=true
      - traefik.http.routers.nameless.tls.certresolver=letsencrypt
      - traefik.http.routers.nameless.tls.domains[0].main=minersonline.uk
      - traefik.http.routers.nameless.tls.domains[0].sans=*.minersonline.uk
    volumes:
      - ./src:/var/www/html:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped
    networks:
      - traefik
      - mccms

networks:
  mccms:
    name: mccms
  traefik:
    external: true
