services:
  gate:
    image: ghcr.io/minekube/gate/jre:latest
    env_file:
      - gate.env
    restart: unless-stopped
    volumes:
      - ./gate/config.yml:/config.yml
      - ./gate/:/gate/
    ports:
      - '25565:25565' # Java Edition
      - '25565:25565/udp' # Java Edition query
      - '19132:19132/udp' # Geyser listener
    networks:
      - minecraft

networks:
  minecraft: