services:
  gate:
    image: ghcr.io/minekube/gate/jre:latest
    env_file:
      - gate.env
    restart: unless-stopped
    volumes:
      - ./gate/config.yml:/config.yml
      - ./gate/:/gate/
    network_mode: host
