services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared_tunnel
    restart: unless-stopped
    env_file: .env
    command: tunnel --no-autoupdate run
    networks:
      - tunnel_net

networks:
  tunnel_net:
    external: true
