services:
  docuwiki:
    image: dokuwiki/dokuwiki:latest
    environment:
      - PHP_TIMEZONE=Europe/London
    volumes:
      - ./dokuwiki_data:/storage
      - ./.htaccess:/var/www/.htaccess
    networks:
      - tunnel_net
    restart: unless-stopped

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared_tunnel
    restart: unless-stopped
    env_file: .env
    command: tunnel --no-autoupdate run
    networks:
      - tunnel_net

networks:
  tunnel_net:
    external: true
